### PR TITLE
Greatly improve scroll experience on trackpads

### LINKED ISSUE #227: Support ballistic scrolling
Track pads are meant to scroll based on how fast the gesture way (deltaY), the scrolling is currently uniform regardless of the gesture. Compare the terminal scroll to the hex editor scroll to see what I'm talking about.

### LINKED ISSUE #228: Improve the experience with a trackpad
On a macbook if you use 2 fingers and drag to the right and then go up, it either won't start scrolling or it will suddenly. I'm guessing there is some filtering of events happening depending on the direction, but I don't think you want to do this for trackpads as it feels clunky unless you also support "diagonal scrolls".

### PR DESCRIPTION
**Pull request by Tyriar**
Adds support for diagonal and ballistic (smooth) scroll events:

recording (12)

Fixes #228
Fixes #227

### CODE REVIEW

**Comment by Tyriar** [comment]
I didn't test this with a mouse, it will probably end up scrolling multiple lines on some machines/browsers, depending on how they fire `WheelEvent`.

**Review by lramos15 — APPROVED** [review]
Thanks! The gif looks really smooth :)

**Comment by lramos15** [comment]
I can test it on a mouse, give me a few minutes

**Comment by lramos15** [comment]
Yeah I would say with a mouse wheel it feels a lot more broken than it does on main. You can scroll super slowly but anything else you jump multiple lines. I would recommend you try it if possible to see what I mean

**Review by lramos15 — CHANGES_REQUESTED** [review]
Want to hold off on merging this until we get a better experience for both mouse and trackpad. As this seems to trade one for the other.

**Comment by Tyriar** [comment]
Sounds good, I'll improve on mouse a bit later.

**Comment by Tyriar** [comment]
@lramos15 ready for another one, not the best fix as it's much harder than you'd expect to differentiate hardware wheel/trackpad, but it should make the experience good on mac.

**Comment by Tyriar** [comment]
Ref for future: https://github.com/xtermjs/xterm.js/blob/145b4874cb217d7c23b46c731a2bb9a780b66c3f/src/browser/Viewport.ts#L27-L30

**Pull request merged**
