### PR TITLE
Add default endianness setting

### PR DESCRIPTION
**Pull request by natecraddock**
This adds a setting to set the endianness selected in the data inspector by default on load. This is useful when working on a large number of big-endian files so the data inspector dropdown doesn't need to be changed each time a new file is opened.

### CODE REVIEW

**Comment by natecraddock** [comment]
The contributing guidelines weren't clear if all pull requests are required to have an associated issue. If that's the case let me know and I will add one!

Also, this is my first time editing a VSCode extension, so hopefully it follows general standards.

**Comment by lramos15** [comment]
Hi @natecraddock. I'll take a look at this this week. Do you mind also updating the README.md file with the new setting, similar to how the other setting is listed

**Comment by natecraddock** [comment]
Thanks! I've updated the readme

**Comment by lramos15** [comment]
@natecraddock Thanks for the quick update and I'm probably going to sound like a broken record. I'm planning to review your PR tomorrow do you mind removing the setting from the readme (Since @Tyriar pointed out it's duplicated in the contributions section and he just did a bunch of README cleanup) and then solve the merge conflicts :)

**Review by Tyriar — COMMENTED** [review]
Instead of using a setting here, would it make more sense to just remember the previous selection made and apply that to new files?

Pros:

- No additional setting to know about/configure

Cons:

- If you frequently work with both, you'd need to switch back to little

**Comment by lramos15** [comment]
If you were to "remember" the setting we would have to have some sort of hex editor config that we right as I'm not sure how the state can be preserved.

**Comment by natecraddock** [comment]
@Tyriar I think a setting is better. In my case, I have a project which uses entirely big endian formatted data, but others that use little endian. The setting makes it easy to configure per-workspace how to interpret the data by default.

Also, with only 3 settings, it's not like there is an overload of too many settings here.

**Review by lramos15 — APPROVED** [review]
Looks good, thanks! I also agree a setting feels cleaner here as the idea of remembering what you picked for previous files would add complexity and might confuse the user.

**Comment by Tyriar** [comment]
Sounds good 🙂

@lramos15 fyi there's apis in the exthost that let you store workspace or user-level info like this

**Comment by lramos15** [comment]
Ooh that's neat. Maybe something to look into in the future 🙂

**Pull request merged**
