### PR TITLE
fix: compile errors

### PR DESCRIPTION
**Pull request by rzhao271**

### CODE REVIEW

**Review by andreamah — DISMISSED** [review]

**Review by Tyriar — DISMISSED** [review]
Do we not have CI to prevent this on this repo?

**Review by lramos15 — CHANGES_REQUESTED** [review]
We need to get CI for this, it's on the list.

Is there a way we can avoid the non null assertions?

**Comment by rzhao271** [comment]
Updating TypeScript could help, though won't get to that for a bit.

**Comment by connor4312** [comment]
We can just remove `pr: none` in the pipeline.yml to get checks for this

**Review by Tyriar — APPROVED** [review]

**Review by connor4312 — APPROVED** [review]

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
