### PR TITLE
add common cjk encoding (gb18030 for simple Chinese, big5 for traditional Chinese, euc-kr for Korean, euc-jp for Japanese) datatype support

### PR DESCRIPTION
**Pull request by liudonghua123**
Closes https://github.com/microsoft/vscode-hexeditor/issues/464.

### CODE REVIEW

**Comment by lramos15** [comment]
I do worry that this will make the data inspector fairly long. I wonder if there's a way we can support all the formats that the TextDecoder supports without adding a bunch of these

**Comment by liudonghua123** [comment]
> I do worry that this will make the data inspector fairly long. I wonder if there's a way we can support all the formats that the TextDecoder supports without adding a bunch of these

Yeah, an interactive `select` element which includes all supported encoding of TextDecoder as options maybe an elegant way.

However, the datatype decode is quick and low resource consumption. And there are a lot remaining free spaces there, so maybe not a problem right now.

**Comment by HaxtonFale** [comment]
Could you please also add Shift-JIS? I believe it's pretty common in a lot of JP executables.

**Comment by liudonghua123** [comment]
From the docs on [Encodings of Japanese](https://www.sljfaq.org/afaq/encodings.html#:~:text=Shift%20JIS%20is%20the%20Microsoft%20encoding%20of%20JIS%2C,systems%2C%20and%20is%20sometimes%20used%20on%20web%20pages). It seems `shift-jis` is more suitable then `euc-jp`. I will update the code for pr.

**Review by connor4312 — APPROVED** [review]
I'll add in some filtering logic after we merge this

**Comment by Young-Lord** [comment]
IMHO, maybe it would be better to allow users to customize encoding(s) to use in configuration file?
或者说，从配置文件读取需要的编码是否会更好？

**Review by lramos15 — APPROVED** [review]

**Pull request merged**
