### PR TITLE
Add in data inspector UUID/GUID

### LINKED ISSUE #499: [Feature request] Add in data inspector UUID/GUID
Show in data inspector the useful 128-bit [UUID/GUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) (Universally Unique Identifier/Globally Unique Identifier) following [RFC 4122](https://datatracker.ietf.org/doc/html/rfc4122)

### PR DESCRIPTION
**Pull request by jogo-**
Show in data inspector the useful 128-bit UUID/GUID (Universally Unique Identifier/Globally Unique Identifier) following RFC 4122 Closes #499

### CODE REVIEW

**Comment by jogo-** [comment]
Commit pushed✔

**Review by connor4312 — APPROVED** [review]

**Review by roblourens — APPROVED** [review]

**Comment by connor4312** [comment]
Thanks for the PR!

**Comment by jogo-** [comment]
You're welcome!

**Comment by jogo-** [comment]
This feature is still missing in latest Hex Editor v1.10.0 / VS Code 1.90.0.
Is it due to broken pipeline?

**Comment by jogo-** [comment]
This feature is still missing in latest Hex Editor v1.10.0 / VS Code 1.90.0.
@connor4312 @roblourens @lramos15 Would you mind please adding this feature in the upcoming VS Code ?
Thank you very much

**Comment by jogo-** [comment]
Unfortunately, this feature is still missing in latest Hex Editor v1.10.0 / VS Code 1.93.0.
@connor4312 @roblourens @lramos15 Would you mind please adding this feature in the upcoming VS Code ?
Thank you very much again

**Pull request merged**
