### PR TITLE
Added search result list

### PR DESCRIPTION
**Pull request by tigerbeard**
Added a button to the search widget to show/hide a list of all search results listed by offset as hex. List entries are clickable for navigation and divided into pages.

Full disclosure: I am not proficient with typescript/javascript and this is my first attempt at working on a VS Code extension, so if my code contains any particularly heinous JS misdeeds, let me apologize ahead of time! =)

### CODE REVIEW

**Comment by tigerbeard** [comment]
So... I guess this project is abandonware now?

**Comment by tigerbeard** [comment]
Ping?

**Comment by lramos15** [comment]
Hi @tigerbeard Sorry for the wait and thank you for your patience as I was completing other work but am now focusing again on this project for a bit. I will review your PR by the end of the week and get back to you :). Thanks for the PR!

**Comment by lramos15** [comment]
Closing this as the number of changes that have occurred since are quite large. Sorry for letting this PR go stale if you would like to pursue this again with all the new changes please let me know and I would be happy to take a look

**Pull request closed without merging**
