### PR TITLE
Implement editing, find/replace in streaming model

### PR DESCRIPTION
**Pull request by connor4312**
This implements editing, include find and replace. Undo/redo doesn't work, I'll toss that in tomorrow morning. After this I'll swap to some of my other iteration work.

### CODE REVIEW

**Review by lramos15 — APPROVED** [review]
👍 . Some comments on those larger functions :). Don't forget to fix the bugs we went over

**Comment by connor4312** [comment]
Fixed a bunch of those, the remainder I will take care of when I return Tuesday

- [ ] length change in modification shows on wrong change (might have fixed already, need to confirm)
- [ ] find/replace back and forth with different lengths breaks
- [x] don't change selected arrow on hover
- [ ] expansion arrow on find/replace widget
- [ ] show error state in find instead of diallowing keypresses
- [x] binary search seems to find wrong
- [x] confirm progress indicator, regex with . not working
- [x] drop opId
- [x] make sure focus is synced to browser focus
- [x] tab should focus the byte in the text side
- [x] check out go to offset / quickpick bugs
- [x] return focus on escape from find widget
- [ ] delete editsequal
- [ ] rename currentEditor to something else
- [ ] reimplement "??"

**Comment by connor4312** [comment]
This should be good to go now. I'll write up a TPI over holiday.

**Review by lramos15 — APPROVED** [review]
👍

**Pull request merged**
