### PR TITLE
Allow a base address to be added to a file via a URI

### PR DESCRIPTION
**Pull request by haneefdm**
I apologize if I didn't do things right. Even tabs vs. spaces. I am not a TypeScript expert either. Please review and I will do whatever is needed.

Basically, even if you are reading a file, the base address is not always zero. This is an awesome extension and I want to use it in a debugger. I am trying to address Issue #70 that I filed. It is only one part of the solution.

**Bottom line: adds an offset to the addresses displayed**

Yes, I have some imports for `fs` as I was using them for debugging and logging. As I found out, debugging two extensions at the same time was a bit challenging.

Btw, `npm install` fails for me because I don't have the `nan` package installed globally. I can fix `package.json` if you want.

### CODE REVIEW

**Comment by haneefdm** [comment]
I want to update the ChangeLog or release notes. Not sure what to update because of another PR #169 pending.

Please advise

**Comment by haneefdm** [comment]
I am now wondering if I followed the process correctly. Could you guys please assign a reviewer(s) when you get a chance. The vscode-cpptools and MIEngine teams are also waiting. Thanks again

**Comment by heartacker** [comment]
@lramos15 please,3q

**Comment by lramos15** [comment]
@haneefdm I promise this is on my radar. I no longer have merge access to this repo as I no longer work at Microsoft (I was a summer intern) and so I've reached out to the VS Code team to see if I'll be doing this review or if they will be doing it. I'm awaiting their response

**Comment by lramos15** [comment]
@mjbvz Do you have any suggestions on how to proceed with this PR?

**Comment by haneefdm** [comment]
I get a feeling this is a dead end. So sad. Such a nice extension and a needed one. Other teams within MS are also waiting for this and they have done a bunch of work as well.

Please, at least one response regarding the future of this extension would be nice. I totally understand corporate priorities change, etc., but please communicate

**Comment by mjbvz** [comment]
@lramos15 Does the change look good to you?

**Comment by lramos15** [comment]
@mjbv Yes this looks good to me, the changes aren't very large. This would of course require a little bit of quick testing and a new version published but I have no issues with these changes

**Comment by mjbvz** [comment]
Published in 1.3.0

**Pull request merged**
